apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "jenkins"
spec:
  storageClassName: manual
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
  volumeName: "jenkins"
