apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "jenkins"
spec:
  storageClassName: manual
  capacity:
    storage: "8Gi"
  accessModes:
    - "ReadWriteOnce"
  awsElasticBlockStore:
    fsType: "ext4"
    volumeID: "vol-01dc558a7e80fc575"
