apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "sonarqube"
spec:
  storageClassName: manual
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "4Gi"
  volumeName: "sonarqube"
